name: Lint and Test Charts

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@dev-v2
        with:
          command: lint
          config: ct.yaml
